### ISSUE TITLE
ios14 访问不了

### ISSUE THREAD

**Issue by Mase9527** [cxymq/ShortcutToHome#2]

**Comment by cxymq** [comment]
**目前高版本应该无法使用。** 

1. **CocoaHTTPServer** 第三方库使用的某些官方 api 被废弃
```
- (instancetype)initWithDomain:(NSString *)domain type:(NSString *)type name:(NSString *)name port:(int)port NS_DESIGNATED_INITIALIZER 
```
需要改成 
```
- (instancetype)initWithDomain:(NSString *)domain type:(NSString *)type name:(NSString *)name
```
```
[theNetService publish];
```
需要改成
```
[theNetService publishWithOptions:NSNetServiceListenForConnections];
```
![image](https://user-images.githubusercontent.com/11361490/130045534-60c5fd9b-367a-448e-9874-ecb2fb59d589.png)

2. 需要增加权限申请

**NSBonjourServices and NSLocalNetworkUsageDescription are required in Info.plist**

```
<key>NSLocalNetworkUsageDescription</key>
<string>允许访问本地网络</string>
<key>NSBonjourServices</key>
    <array>
	    <string>_http._tcp.</string>
    </array>
```

3. 苹果禁用代码调用 Safari 的 Data URI Scheme 功能
Safari redirect to base64 encoded html fails on iOS 14 （https://developer.apple.com/forums/thread/650034）

**Comment by cxymq** [comment]
![image](https://user-images.githubusercontent.com/11361490/130050118-f0ccb57b-9973-49e0-8407-c94c40b2a9e2.png)
参考支付宝的做法，不再访问 127.0.0.1 展示本地 H5，而是一个线上 H5

**Comment by cxymq** [comment]
参考支付宝的做法，是打开一个线上 H5（截图中的 appId 需要更换，或者自己本机生成支付宝的快捷桌面，获取这个链接
![image](https://user-images.githubusercontent.com/11361490/130050802-4dad4ca5-71de-4956-836a-80489f8c3188.png)
